SubscriptionBond (inc. Websocket, more accurate notifications)
paritytech/oo7-parity pull request #3
Opened 2017-06-14 13:57 UTC by kaikun213

In progress. (still dependent on new parity-js pubsub feature)

2017-06-23 10:38 UTC, kaikun213 commented
For Bonds which take an input and are not likely that the result will change frequently we maybe should stay with the api calls. E.g. bonds.blockByNumber will likely change the given number often which would lead to a new unsubscribe/subscribe its much less likely that the returned block is another one (only reorgs). However a subscriptionBond insteadof api call will always send one more message (request-response-response) instead of simple request-response.

2017-06-23 11:33 UTC, gavofyork commented
Best, I think, to keep everything consistent and correct for now with `SubscriptionBond` use throughout., 

If speed becomes an issue we can revisit later.

2017-06-23 17:32 UTC, gavofyork requested changes

2017-06-23 17:32 UTC, gavofyork commented on src/index.js
> +			this.options = [(_,n) => this.trigger(n), ...options];
missing space after `,`

2017-06-23 17:32 UTC, gavofyork commented on src/index.js
> +					return new TransformBond(f, [this]);
incorrect tabbing - `}` should be indented as much as the line that has the matching `{` on.

2017-06-23 17:32 UTC, gavofyork commented on src/index.js
> +	bonds.allAccountsInfo = bonds.accounts;	// double?
incorrect - `allAccountsInfo` is a completely different API.

2017-06-23 17:32 UTC, gavofyork commented on src/index.js
> +    Function.__proto__.blockBond = function(...args) { return new TransformBond(this, args, [bonds.height]); };
tabs not spaces (also the original line above needs correcting)

2017-06-23 17:34 UTC, gavofyork commented on src/index.js
> +					return new TransformBond(f, [this]);
also, i had replaced this with the implementation from above. that should be used now:

```
map (f, outResolveDepth = 0, resolveDepth = 1) {
 	        return new TransformBond(f, [this], [], outResolveDepth, resolveDepth);
}
```

2017-06-23 17:36 UTC, gavofyork commented on src/index.js
>  		sub (name) {
sub (name, outResolveDepth = 0, resolveDepth = 1) {
	return new TransformBond((r, n) => r[n], [this, name], [], outResolveDepth, resolveDepth);
}

2017-07-06 13:39 UTC, kaikun213 commented
@gavofyork parity-pubsub is merged in master. Could soon be merged?

2017-10-20 19:20 UTC, gavofyork commented
just use #5.

2017-10-20 19:20 UTC, closed without merging