Updates
paritytech/oo7-parity pull request #7
Opened 2017-09-26 14:05 UTC by jacogr

- Add editorconfig & eslint
- eslint fixes
- split ABI json into individual files
- add license headers to all files

2017-10-20 18:10 UTC, gavofyork commented
looks good but will need resolving.

2017-10-20 18:10 UTC, gavofyork requested changes
needs resolving

2017-10-20 18:36 UTC, jacogr commented
Thanks, will update.

2017-10-21 13:13 UTC, gavofyork commented
superceded by #10

2017-10-21 13:13 UTC, closed without merging